ALTER TABLE "order_items"
ADD COLUMN IF NOT EXISTS "unit_price" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "line_total" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "is_manual_priced" BOOLEAN NOT NULL DEFAULT false;
